title: "How on-screen emotions make money?"
baseurl: "/on-screen-emotions"
favicon: "assets/images/favicon.ico"
font: '"Rubik", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif'
load_google_fonts: "Rubik:400,400italic,700,700italic"
author: LEGO
locale: en_us
lang: en_us
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed

# Authors
authors:
  sal:
    name: Ondin
    display_name: Ondin
    avatar: "assets/images/ondin.png"
    email: kafkaon1@gmail.com
    github: https://github.com/ondin
    description: "Usak."
  john:
    name: Ondin
    display_name: Ondin
    avatar: "assets/images/ondin.png"
    email: kafkaon1@gmail.com
    github: https://github.com/ondin
    description: "Usak."

# Plugins
plugins:
  - jekyll-archives
